FROM python:3.11-slim

WORKDIR /app

# Instalacja zależności systemowych dla kompilacji i obsługi PostgreSQL
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Kopiowanie i instalacja pakietów Pythona
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Kopiowanie kodu źródłowego
COPY . .

# Wystawienie portu dla FastAPI
EXPOSE 8000

# Start aplikacji za pomocą asynchronicznego serwera Uvicorn
CMD ["python", "main.py"]
